# Generated by Django 4.2.20 on 2025-04-12 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="个人简介"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女")],
                default="M",
                max_length=1,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="兴趣爱好"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="是否在线"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="最后活跃时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所在地"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="用户", max_length=50, verbose_name="昵称"),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="喜欢者",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被喜欢者",
                    ),
                ),
            ],
            options={
                "verbose_name": "喜欢关系",
                "verbose_name_plural": "喜欢关系",
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
